$(document).ready(function(){
    $('main').append("<button id='clickyButton'>Resume?</button>");
    $("#clickyButton").click(function(){
        $(".wrap").slideToggle(2000);
    });
    $(".clickHeading").click(function(){
        $(".showHeading").slideDown(2000);
        $(".clickHeading").hide();
    });
    $(".showHeading").click(function(){
        $(".showHeading").slideUp(2000);
        $(".clickHeading").show();
    });
    $(".clickEducation").click(function(){
        $(".showEducation").slideToggle(2000);
    });
    $(".clickExperience").click(function(){
        $(".showExperience").slideToggle(2000);
    });
});
